### ISSUE TITLE
Booking Status Tracking

### ISSUE THREAD

**Issue by anupamroy8** [anupamroy8/porters-app#2]
- [ ]  Add `status` field to `Booking` model (e.g., `pending`, `confirmed`, `in_transit`, etc.)
- [ ]  Create methods to update status at various stages
- [ ]  Add notifications to alert users of status changes
